### ISSUE TITLE
undefined local variable or method `defaults' for #<Class:0xd521c48>

### ISSUE THREAD

**Issue by Sh1n1x** [evrone/rails-settings-ui#2]
Hi, 

When i try to add your gem in my project i get this error with the model "Setting.rb"  

> undefined local variable or method `defaults' for #Class:0xd521c48

```
class Setting < RailsSettings::CachedSettings
    defaults[:company_name] = "Test"
end
```

And this is my config/initializers/rails_settings_ui.rb

```
require 'rails-settings-ui'
Rails.application.config.to_prepare do
  RailsSettingsUi::ApplicationController.module_eval { layout 'administration' }

  # If you use a *custom layout*, make route helpers available to RailsSettingsUi:
  RailsSettingsUi.inline_main_app_routes!
end
RailsSettingsUi.settings_class = "Setting"

```

i'm not understand because this code work fine with an another project.

Thanks !

**Comment by accessd** [comment]
Hi! On which line this error happens? Please provide full error trace.

And official repo is https://github.com/accessd/rails-settings-ui, try to use last version of that.

**Comment by Sh1n1x** [comment]
Hi !

Finally it's working fine, but the latest version of Rails-settings-cache not working for me with the latest rails-settings-ui.

I've added in my GemFile : 

`gem 'rails-settings-ui', :git => 'git://github.com/accessd/rails-settings-ui.git'`
`gem "rails-settings-cached", '0.5.4'`

**Comment by dischmidt** [comment]
Working with 0.6.5

It does not work with defaults[] anymore. I had to include in app.yml the following
```
1 defaults:
2   example_var: 'example_value'`
3   defaults:
4     :example_var: 'example_value'`
```
The YAML code creates the defaults value but as well the default_var with the value .... the code seems not to be clever enough to reuse the data. The two colons at row 4 are necessary for YAML creating a hash named defaults. An array does not work.

**Comment by rimidl** [comment]
Sorry, this repo is deprecated. But you can find the same project here - https://github.com/accessd/rails-settings-ui.
